from dataclasses import dataclass
import json
from typing import Optional

import pytest
from snowflake.connector import DictCursor

from lib.config_migration import V4_CONFIG_TEMPLATE
from lib.driver import KafkaDriver
from lib.fixtures.table import Table


@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
@pytest.mark.parametrize(
    "sanitize_autogenerated_table_names",
    [True, False],
    ids=["sanitized", "unsanitized"],
)
def test_high_performance_case_sensitivity_table_name(
    driver: KafkaDriver,
    create_connector,
    create_topics,
    name_salt,
    wait_for_rows,
    sanitize_autogenerated_table_names,
):
    """Assert table name derived by the connector matches our expectations."""

    @dataclass(frozen=True)
    class TableNameCase:
        case_name: str  # description
        unsalted_topic_name: str
        topic2table_value: Optional[str]
        expected_table_name: str

    test_cases = [
        # Without topic2table.map, the connector passes the topic name as the table name.
        # With sanitization disabled, that name is passed as-is, i.e. not uppercased.
        TableNameCase(
            case_name="lower_a",
            unsalted_topic_name="a",
            topic2table_value=None,
            expected_table_name=f"A{name_salt}"
            if sanitize_autogenerated_table_names
            else f"a{name_salt}",
        ),
        TableNameCase(
            case_name="upper_b",
            unsalted_topic_name="B",
            topic2table_value=None,
            expected_table_name=f"B{name_salt}",
        ),
        TableNameCase(
            case_name="lower_c_mapped",
            unsalted_topic_name="c_topic",
            topic2table_value=f"c{name_salt}",
            expected_table_name=f"C{name_salt}",
        ),
        TableNameCase(
            case_name="upper_d_mapped",
            unsalted_topic_name="D_topic",
            topic2table_value=f"D{name_salt}",
            expected_table_name=f"D{name_salt}",
        ),
        TableNameCase(
            case_name="lower_e_mapped_quoted",
            unsalted_topic_name="e_topic",
            topic2table_value=f'"e{name_salt}"',
            expected_table_name=f"e{name_salt}",
        ),
        TableNameCase(
            case_name="upper_f_mapped_quoted",
            unsalted_topic_name="f_topic",
            topic2table_value=f'"F{name_salt}"',
            expected_table_name=f"F{name_salt}",
        ),
        TableNameCase(
            case_name="unicode_mapped_quoted",
            unsalted_topic_name="g_topic",
            topic2table_value=f'"❄️{name_salt}"',
            expected_table_name=f"❄️{name_salt}",
        ),
    ]

    topics = create_topics(
        [test_case.unsalted_topic_name for test_case in test_cases], with_tables=False
    )

    topic2table_map = ",".join(
        f"{test_case.unsalted_topic_name}{name_salt}:{test_case.topic2table_value}"
        for test_case in test_cases
        if test_case.topic2table_value is not None
    )

    connector = create_connector(
        v4_config={
            key: value
            for key, value in {
                **V4_CONFIG_TEMPLATE,
                "topics": ",".join(topics),
                "snowflake.topic2table.map": topic2table_map,
                "key.converter": "org.apache.kafka.connect.storage.StringConverter",
                "value.converter": "org.apache.kafka.connect.json.JsonConverter",
                "value.converter.schemas.enable": "false",
                # high-performance defaults, but we also test with sanitized table names
                "snowflake.validation": "server_side",
                "snowflake.compatibility.enable.column.identifier.normalization": "false",
                "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true"
                if sanitize_autogenerated_table_names
                else "false",
            }.items()
            if value is not None
        }
    )
    driver.startConnectorWaitTime()

    for test_case in test_cases:
        driver.sendBytesData(
            f"{test_case.unsalted_topic_name}{name_salt}",
            [json.dumps({"case_name": test_case.case_name}).encode("utf-8")],
        )

    for test_case in test_cases:
        expected_table = Table(driver, test_case.expected_table_name)
        wait_for_rows(expected_table.name, 1, connector_name=connector.name)

        tables = (
            driver.snowflake_conn.cursor(DictCursor).execute("show tables").fetchall()
        )
        assert test_case.expected_table_name in [table["name"] for table in tables]

        # Make sure it's the correct one, i.e. has the data we sent it.
        assert expected_table.select_scalar("CASE_NAME") == test_case.case_name

    # Cleanup - first remove the connector, then the tables.
    connector.close()
    for test_case in test_cases:
        Table(driver, test_case.expected_table_name).drop()
