package com.snowflake.kafka.connector.config;

import com.snowflake.kafka.connector.ConnectorConfigTools;
import com.snowflake.kafka.connector.Constants.KafkaConnectorConfigParams;
import com.snowflake.kafka.connector.internal.CachingConfig;
import com.snowflake.kafka.connector.records.SnowflakeMetadataConfig;
import java.util.Collections;
import java.util.HashMap;

/**
 * Test-only builder for {@link SinkTaskConfig}. Provides a builder with default values for all
 * optional fields. Caller must set connectorName and taskId before build().
 *
 * <p>Production code uses {@link SinkTaskConfig#from(java.util.Map)}; this class is for tests that
 * need to construct a config without parsing a Map.
 */
public final class SinkTaskConfigTestBuilder {

  private SinkTaskConfigTestBuilder() {}

  /**
   * Returns a builder with default values for all optional fields. Caller must set connectorName
   * and taskId before build().
   */
  public static SinkTaskConfig.Builder builder() {
    return SinkTaskConfig.builder()
        .topicToTableMap(new HashMap<>())
        .behaviorOnNullValues(ConnectorConfigTools.BehaviorOnNullValues.DEFAULT)
        .jmxEnabled(KafkaConnectorConfigParams.JMX_OPT_DEFAULT)
        .tolerateErrors(false)
        .errorsLogEnable(KafkaConnectorConfigParams.ERRORS_LOG_ENABLE_DEFAULT)
        .dlqTopicName(KafkaConnectorConfigParams.ERRORS_DEAD_LETTER_QUEUE_TOPIC_NAME_DEFAULT)
        .enableSanitization(
            KafkaConnectorConfigParams
                .SNOWFLAKE_ENABLE_AUTOGENERATED_TABLE_NAME_SANITIZATION_DEFAULT)
        .enableSchematization(KafkaConnectorConfigParams.SNOWFLAKE_ENABLE_SCHEMATIZATION_DEFAULT)
        .clientValidationEnabled(
            KafkaConnectorConfigParams.SNOWFLAKE_CLIENT_VALIDATION_ENABLED_DEFAULT)
        .openChannelIoThreads(KafkaConnectorConfigParams.SNOWFLAKE_OPEN_CHANNEL_IO_THREADS_DEFAULT)
        .streamingClientProviderOverrideMap("")
        .cachingConfig(CachingConfig.fromConfig(Collections.emptyMap()))
        .metadataConfig(new SnowflakeMetadataConfig())
        .snowflakeUrl("")
        .snowflakeUser("")
        .snowflakeRole("")
        .snowflakePrivateKey("")
        .snowflakePrivateKeyPassphrase("")
        .snowflakeDatabase("")
        .snowflakeSchema("");
  }
}
