package com.snowflake.kafka.connector.config;

import com.snowflake.kafka.connector.ConnectorConfigTools;
import com.snowflake.kafka.connector.Constants.KafkaConnectorConfigParams;
import com.snowflake.kafka.connector.StaticTopicToTableResolver;
import com.snowflake.kafka.connector.internal.CachingConfig;
import com.snowflake.kafka.connector.internal.streaming.v2.migration.Ssv1MigrationMode;
import com.snowflake.kafka.connector.records.SnowflakeMetadataConfig;
import java.util.Collections;
import java.util.Map;

/**
 * Test-only builder for {@link SinkTaskConfig}. Provides a builder with default values for all
 * optional fields. Caller must set connectorName and taskId before build().
 *
 * <p>Production code uses {@link SinkTaskConfig#from(java.util.Map)}; this class is for tests that
 * need to construct a config without parsing a Map.
 */
public final class SinkTaskConfigTestBuilder {

  private SinkTaskConfigTestBuilder() {}

  /**
   * Returns a builder with default values for all optional fields. Caller must set connectorName
   * and taskId before build().
   */
  public static SinkTaskConfig.Builder builder() {
    return SinkTaskConfig.builder()
        .topicToTableResolver(new StaticTopicToTableResolver(Map.of()))
        .behaviorOnNullValues(ConnectorConfigTools.BehaviorOnNullValues.DEFAULT)
        .jmxEnabled(KafkaConnectorConfigParams.JMX_OPT_DEFAULT)
        .tolerateErrors(false)
        .errorsLogEnable(KafkaConnectorConfigParams.ERRORS_LOG_ENABLE_DEFAULT)
        .dlqTopicName(KafkaConnectorConfigParams.ERRORS_DEAD_LETTER_QUEUE_TOPIC_NAME_DEFAULT)
        .enableSanitization(
            KafkaConnectorConfigParams
                .SNOWFLAKE_COMPATIBILITY_ENABLE_AUTOGENERATED_TABLE_NAME_SANITIZATION_DEFAULT)
        .enableColumnIdentifierNormalization(
            KafkaConnectorConfigParams
                .SNOWFLAKE_COMPATIBILITY_ENABLE_COLUMN_IDENTIFIER_NORMALIZATION_DEFAULT)
        .enableSchematization(KafkaConnectorConfigParams.SNOWFLAKE_ENABLE_SCHEMATIZATION_DEFAULT)
        .validation(
            SnowflakeValidation.fromConfig(KafkaConnectorConfigParams.SNOWFLAKE_VALIDATION_DEFAULT))
        .openChannelIoThreads(KafkaConnectorConfigParams.SNOWFLAKE_OPEN_CHANNEL_IO_THREADS_DEFAULT)
        .streamingClientProviderOverrideMap("")
        .cachingConfig(CachingConfig.fromConfig(Collections.emptyMap()))
        .metadataConfig(new SnowflakeMetadataConfig())
        .snowflakeUrl("")
        .snowflakeUser("")
        .snowflakeRole("")
        .authenticator(AuthenticatorType.SNOWFLAKE_JWT)
        .oauthIncludeScope(KafkaConnectorConfigParams.SNOWFLAKE_OAUTH_INCLUDE_SCOPE_DEFAULT)
        .snowflakeDatabase("")
        .snowflakeSchema("")
        .ssv1MigrationMode(Ssv1MigrationMode.SKIP)
        .ssv1MigrationIncludeConnectorName(false)
        .assertPartitionAssignmentEnabled(true)
        .precommitClientRecoveryEnabled(true)
        .prometheusMetricsEnabled(KafkaConnectorConfigParams.PROMETHEUS_ENABLE_DEFAULT)
        .validationErrorTableNameEnabled(
            KafkaConnectorConfigParams.SNOWFLAKE_FEATURE_VALIDATION_ERROR_TABLE_NAME_DEFAULT)
        // Iceberg auto-creation defaults: SNOWFLAKE table type and empty create options.
        // These were previously defaulted in SinkTaskConfig.builder(); they now live here so
        // production builder() stays free of test-only defaults.
        .tableType(
            TableType.fromConfig(KafkaConnectorConfigParams.SNOWFLAKE_AUTOCREATE_TABLE_TYPE_DEFAULT)
                .orElse(TableType.SNOWFLAKE))
        .icebergCreateTableOptions(
            KafkaConnectorConfigParams.SNOWFLAKE_ICEBERG_CREATE_TABLE_OPTIONS_DEFAULT);
  }
}
