"""Config migration between KC v3 and v4 connector configurations."""

import copy
from typing import Dict

V4_CONNECTOR_CLASS = "com.snowflake.kafka.connector.SnowflakeStreamingSinkConnector"
V3_CONNECTOR_CLASS = "com.snowflake.kafka.connector.SnowflakeSinkConnector"

V3_CONFIG_TEMPLATE = {
    "connector.class": V3_CONNECTOR_CLASS,
    "snowflake.ingestion.method": "SNOWPIPE_STREAMING",
    # placeholders for templating
    "snowflake.url.name": "SNOWFLAKE_HOST",
    "snowflake.user.name": "SNOWFLAKE_USER",
    "snowflake.private.key": "SNOWFLAKE_PRIVATE_KEY",
    "snowflake.database.name": "SNOWFLAKE_DATABASE",
    "snowflake.schema.name": "SNOWFLAKE_SCHEMA",
    "snowflake.role.name": "SNOWFLAKE_ROLE",
    # make tests fast
    "buffer.flush.time": "1",
    "snowflake.streaming.max.client.lag": "1",
}

V4_CONFIG_TEMPLATE = {
    "connector.class": V4_CONNECTOR_CLASS,
    # placeholders for templating
    "snowflake.url.name": "SNOWFLAKE_HOST",
    "snowflake.user.name": "SNOWFLAKE_USER",
    "snowflake.private.key": "SNOWFLAKE_PRIVATE_KEY",
    "snowflake.database.name": "SNOWFLAKE_DATABASE",
    "snowflake.schema.name": "SNOWFLAKE_SCHEMA",
    "snowflake.role.name": "SNOWFLAKE_ROLE",
}


def v4_config_to_v3(config: Dict[str, str]) -> Dict[str, str]:
    """Convert a v4 connector config to v3 equivalent."""
    v3 = copy.deepcopy(config)
    v3["connector.class"] = V3_CONNECTOR_CLASS
    v3["snowflake.ingestion.method"] = "SNOWPIPE_STREAMING"
    # v3 defaults to schematization off; v4 defaults to on.
    # Preserve v4's default by setting it explicitly for v3 when unspecified.
    v3.setdefault("snowflake.enable.schematization", "true")
    v3.setdefault("buffer.flush.time", "1")
    v3.setdefault("snowflake.streaming.max.client.lag", "1")
    # Map v4 include-connector-name back to the v3 channel naming flag
    include_connector_name = v3.pop(
        "snowflake.streaming.classic.offset.migration.include.connector.name", None
    )
    if include_connector_name is not None:
        v3.setdefault(
            "snowflake.streaming.channel.name.include.connector.name",
            include_connector_name,
        )
    # Strip v4-only settings.
    v3.pop("snowflake.streaming.classic.offset.migration", None)
    return v3


def v3_config_to_v4(config: Dict[str, str]) -> Dict[str, str]:
    """Convert a v3 connector config to v4 equivalent."""
    v4 = copy.deepcopy(config)
    v4["connector.class"] = V4_CONNECTOR_CLASS

    # === Deprecated settings ===
    v4.pop("snowflake.ingestion.method", None)

    # === New defaults ===
    # v4 defaults to schematization on; v3 defaults to off.
    # Preserve v3's default by setting it explicitly for v4 when unspecified.
    v4.setdefault("snowflake.enable.schematization", "false")

    # === Compatibility settings ===
    v4["snowflake.validation"] = "client_side"
    v4["snowflake.compatibility.enable.column.identifier.normalization"] = "true"
    v4["snowflake.compatibility.enable.autogenerated.table.name.sanitization"] = "true"

    # If v3 used connector-name-prefixed channel naming, carry it over so
    # the SSv1 offset migration lookup uses the matching channel name format.
    include_connector_name = v4.pop(
        "snowflake.streaming.channel.name.include.connector.name", None
    )
    # IMPORTANT NOTE: In previous versions of the connector, the behavior was not controlled by this setting and exhibited the implicit effective value:
    # - v2.0.0–v2.0.1: always false; no streaming channel name prefix.
    # - v2.1.0–v2.1.1: always true (hardcoded connector name prefix, no config knob).
    # - v2.1.2–v2.5.0: always false; v2.1.2 reverted to V1 naming with automatic migration.
    # - v3.0.0–v3.3.1: always false; the setting did not exist.
    # - v3.4.0–v3.5.3: configurable (default false); the setting was introduced here.
    if include_connector_name is not None:
        v4.setdefault(
            "snowflake.streaming.classic.offset.migration.include.connector.name",
            include_connector_name,
        )

    return v4
