# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sensor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sensor.proto',
  package='com.snowflake.kafka.test.protobuf',
  syntax='proto3',
  serialized_options=b'B\021SensorReadingImpl',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csensor.proto\x12!com.snowflake.kafka.test.protobuf\"\xa8\x01\n\rSensorReading\x12G\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x37.com.snowflake.kafka.test.protobuf.SensorReading.Device\x12\x10\n\x08\x64\x61teTime\x18\x02 \x01(\x03\x12\x0f\n\x07reading\x18\x03 \x01(\x01\x1a+\n\x06\x44\x65vice\x12\x10\n\x08\x64\x65viceID\x18\x01 \x01(\t\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x42\x13\x42\x11SensorReadingImplb\x06proto3'
)




_SENSORREADING_DEVICE = _descriptor.Descriptor(
  name='Device',
  full_name='com.snowflake.kafka.test.protobuf.SensorReading.Device',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deviceID', full_name='com.snowflake.kafka.test.protobuf.SensorReading.Device.deviceID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enabled', full_name='com.snowflake.kafka.test.protobuf.SensorReading.Device.enabled', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=220,
)

_SENSORREADING = _descriptor.Descriptor(
  name='SensorReading',
  full_name='com.snowflake.kafka.test.protobuf.SensorReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='device', full_name='com.snowflake.kafka.test.protobuf.SensorReading.device', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dateTime', full_name='com.snowflake.kafka.test.protobuf.SensorReading.dateTime', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reading', full_name='com.snowflake.kafka.test.protobuf.SensorReading.reading', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SENSORREADING_DEVICE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=220,
)

_SENSORREADING_DEVICE.containing_type = _SENSORREADING
_SENSORREADING.fields_by_name['device'].message_type = _SENSORREADING_DEVICE
DESCRIPTOR.message_types_by_name['SensorReading'] = _SENSORREADING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SensorReading = _reflection.GeneratedProtocolMessageType('SensorReading', (_message.Message,), {

  'Device' : _reflection.GeneratedProtocolMessageType('Device', (_message.Message,), {
    'DESCRIPTOR' : _SENSORREADING_DEVICE,
    '__module__' : 'sensor_pb2'
    # @@protoc_insertion_point(class_scope:com.snowflake.kafka.test.protobuf.SensorReading.Device)
    })
  ,
  'DESCRIPTOR' : _SENSORREADING,
  '__module__' : 'sensor_pb2'
  # @@protoc_insertion_point(class_scope:com.snowflake.kafka.test.protobuf.SensorReading)
  })
_sym_db.RegisterMessage(SensorReading)
_sym_db.RegisterMessage(SensorReading.Device)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
