"""Recovery after CREATE OR REPLACE TABLE.

Migrated from v3 ``TestSchemaEvolutionDropTable``.

Pre-creates a table with the full schema, ingests records, then replaces
the table with CREATE OR REPLACE TABLE. The connector should detect the
channel invalidation, re-open the channel, and re-evolve the schema
from scratch.

NOTE: The table is pre-created with all columns to avoid triggering
schema evolution DDL (ALTER TABLE ADD COLUMN) during Wave 1. In SSv2,
ALTER TABLE DDL invalidates the pipe, which can cause data loss in
the current SDK. This test focuses on CREATE OR REPLACE TABLE recovery.
"""

import json

import pytest

from lib.config_migration import V4_CONFIG_TEMPLATE
from lib.driver import quote_name

RECORD_COUNT = 100

RECORD = {
    "PERFORMANCE_STRING": "Excellent",
    "PERFORMANCE_CHAR": "A",
    "RATING_INT": 100,
}

GOLD_TYPES = {
    "PERFORMANCE_STRING": "VARCHAR",
    "PERFORMANCE_CHAR": "VARCHAR",
    "RATING_INT": "NUMBER",
    "RECORD_METADATA": "VARIANT",
}

FULL_TABLE_DDL = (
    "(RECORD_METADATA VARIANT, "
    "PERFORMANCE_STRING VARCHAR, "
    "PERFORMANCE_CHAR VARCHAR, "
    "RATING_INT NUMBER) "
    "ENABLE_SCHEMA_EVOLUTION = TRUE"
)


def _assert_schema(driver, table_name):
    cols = {
        row[0]: row[1]
        for row in driver.snowflake_conn.cursor()
        .execute(f"DESCRIBE TABLE {quote_name(table_name)}")
        .fetchall()
    }
    for col_name, expected_prefix in GOLD_TYPES.items():
        assert col_name in cols, f"Missing column {col_name}, got: {list(cols.keys())}"
        assert cols[col_name].startswith(expected_prefix), (
            f"Column {col_name}: expected {expected_prefix}, got {cols[col_name]}"
        )


def _send_records(driver, topic, count):
    keys = [json.dumps({"number": str(i)}).encode("utf-8") for i in range(count)]
    values = [json.dumps(RECORD).encode("utf-8") for _ in range(count)]
    driver.sendBytesData(topic, values, keys)


@pytest.mark.schema_evolution
@pytest.mark.compatibility
@pytest.mark.parametrize("connector_version", ["v3", "v4"], indirect=True)
def test_se_replace_table(
    driver,
    connector_version,
    name_salt,
    create_connector,
    wait_for_rows,
):
    """CREATE OR REPLACE TABLE mid-stream: connector detects channel invalidation,
    re-opens the channel, and re-evolves the schema from scratch.
    """
    topic = f"se_replace_table{name_salt}"
    # Sanitization uppercases the auto-generated table name, which is
    # required for the v4 SDK whose streaming API resolves pipe names
    # case-insensitively.
    table_name = topic.upper()

    driver.createTopics(topic, partitionNum=1, replicationNum=1)

    # Pre-create the table with the full schema so Wave 1 doesn't trigger
    # schema evolution DDL (which invalidates the SSv2 pipe).
    driver.snowflake_conn.cursor().execute(
        f"CREATE TABLE IF NOT EXISTS {quote_name(table_name)} {FULL_TABLE_DDL}"
    )

    create_connector(
        v4_config={
            **V4_CONFIG_TEMPLATE,
            "topics": topic,
            "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true",
            "snowflake.validation": "client_side",
            "errors.tolerance": "none",
            "errors.log.enable": "true",
            "tasks.max": "1",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter",
            "value.converter": "org.apache.kafka.connect.json.JsonConverter",
            "value.converter.schemas.enable": "false",
        }
    )
    driver.startConnectorWaitTime()

    try:
        # Wave 1: ingest into pre-created table
        _send_records(driver, topic, RECORD_COUNT)
        wait_for_rows(table_name, RECORD_COUNT)
        _assert_schema(driver, table_name)

        # Replace the table (simulating an ops incident)
        driver.snowflake_conn.cursor().execute(
            f"CREATE OR REPLACE TABLE {quote_name(table_name)} "
            f"(RECORD_METADATA VARIANT) "
            f"ENABLE_SCHEMA_EVOLUTION = TRUE"
        )

        # Wave 2: connector should re-evolve the missing columns
        _send_records(driver, topic, RECORD_COUNT)
        wait_for_rows(table_name, RECORD_COUNT)
        _assert_schema(driver, table_name)
    finally:
        driver.drop_table(table_name)
