"""Recovery with multiple topics after a mid-stream table replacement.

Migrated from v3 ``TestSchemaEvolutionMultiTopicDropTable``.

Two topics with different schemas feed into one table. The table is
pre-created with the full schema. After the first wave is ingested
the table is replaced with CREATE OR REPLACE TABLE. The connector
must detect the channel invalidation, re-open channels, and
re-evolve columns from both topics.

NOTE: The table is pre-created with all columns to avoid triggering
schema evolution DDL (ALTER TABLE ADD COLUMN) during Wave 1. In SSv2,
ALTER TABLE DDL invalidates the pipe, which can cause data loss in
the current SDK.
"""

import json

import pytest

from lib.config_migration import V4_CONFIG_TEMPLATE
from lib.driver import quote_name

RECORD_COUNT = 100

RECORDS = [
    {
        "PERFORMANCE_STRING": "Excellent",
        "PERFORMANCE_CHAR": "A",
        "RATING_INT": 100,
    },
    {
        "PERFORMANCE_STRING": "Excellent",
        "RATING_DOUBLE": 0.99,
        "APPROVAL": True,
    },
]

GOLD_TYPES = {
    "PERFORMANCE_STRING": "VARCHAR",
    "PERFORMANCE_CHAR": "VARCHAR",
    "RATING_INT": "NUMBER",
    "RATING_DOUBLE": "FLOAT",
    "APPROVAL": "BOOLEAN",
    "RECORD_METADATA": "VARIANT",
}

FULL_TABLE_DDL = (
    "(RECORD_METADATA VARIANT, "
    "PERFORMANCE_STRING VARCHAR, "
    "PERFORMANCE_CHAR VARCHAR, "
    "RATING_INT NUMBER, "
    "RATING_DOUBLE FLOAT, "
    "APPROVAL BOOLEAN) "
    "ENABLE_SCHEMA_EVOLUTION = TRUE"
)


def _assert_schema(driver, table_name):
    cols = {
        row[0]: row[1]
        for row in driver.snowflake_conn.cursor()
        .execute(f"DESCRIBE TABLE {quote_name(table_name)}")
        .fetchall()
    }
    for col_name, expected_prefix in GOLD_TYPES.items():
        assert col_name in cols, f"Missing column {col_name}, got: {list(cols.keys())}"
        assert cols[col_name].startswith(expected_prefix), (
            f"Column {col_name}: expected {expected_prefix}, got {cols[col_name]}"
        )


def _send_all(driver, topics, count):
    for i, topic in enumerate(topics):
        keys = [json.dumps({"number": str(e)}).encode("utf-8") for e in range(count)]
        values = [json.dumps(RECORDS[i]).encode("utf-8") for _ in range(count)]
        driver.sendBytesData(topic, values, keys)


@pytest.mark.schema_evolution
@pytest.mark.compatibility
@pytest.mark.parametrize("connector_version", ["v3", "v4"], indirect=True)
def test_se_multi_topic_replace_table(
    driver,
    connector_version,
    name_salt,
    create_connector,
    wait_for_rows,
):
    """CREATE OR REPLACE TABLE mid-stream with multiple topics: connector detects
    channel invalidation, re-opens channels, and re-evolves columns from both topics.
    """
    base = f"se_multi_topic_replace_table{name_salt}"
    # Sanitization uppercases auto-generated table names. The multi-topic
    # map values are also uppercase so the connector, table, and SDK all
    # agree on the same (uppercase) name.
    table_name = base.upper()
    topics = [f"{base}{i}" for i in range(2)]

    for t in topics:
        driver.createTopics(t, partitionNum=1, replicationNum=1)

    # Pre-create the table with the full schema so Wave 1 doesn't trigger
    # schema evolution DDL (which invalidates the SSv2 pipe).
    driver.snowflake_conn.cursor().execute(
        f"CREATE TABLE IF NOT EXISTS {quote_name(table_name)} {FULL_TABLE_DDL}"
    )

    create_connector(
        v4_config={
            **V4_CONFIG_TEMPLATE,
            "topics": ",".join(topics),
            "snowflake.topic2table.map": ",".join(f"{t}:{table_name}" for t in topics),
            "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true",
            "snowflake.validation": "client_side",
            "errors.tolerance": "none",
            "errors.log.enable": "true",
            "tasks.max": "1",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter",
            "value.converter": "org.apache.kafka.connect.json.JsonConverter",
            "value.converter.schemas.enable": "false",
        }
    )
    driver.startConnectorWaitTime()

    try:
        # Wave 1
        _send_all(driver, topics, RECORD_COUNT)
        wait_for_rows(table_name, RECORD_COUNT * len(topics))
        _assert_schema(driver, table_name)

        # Replace the table
        driver.snowflake_conn.cursor().execute(
            f"CREATE OR REPLACE TABLE {quote_name(table_name)} "
            f"(RECORD_METADATA VARIANT) "
            f"ENABLE_SCHEMA_EVOLUTION = TRUE"
        )

        # Wave 2
        _send_all(driver, topics, RECORD_COUNT)
        wait_for_rows(table_name, RECORD_COUNT * len(topics))
        _assert_schema(driver, table_name)
    finally:
        driver.drop_table(table_name)
