name: Build Connector
description: Build the Snowflake Kafka Connector JAR/ZIP for a given platform

inputs:
  platform:
    description: "Target platform: 'apache' or 'confluent'"
    required: true

runs:
  using: composite
  steps:
    - name: Install Java 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 11

    - name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: >
          ${{ runner.os }}-maven-${{ hashFiles(
          case(inputs.platform == 'confluent', '**/pom_confluent.xml', '**/pom.xml')
          ) }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build connector
      shell: bash
      working-directory: test
      run: ./build_runtime_jar.sh ../../snowflake-kafka-connector package "$PLATFORM"
      env:
        SNOWFLAKE_CREDENTIAL_FILE: "../profile.json"
        PLATFORM: ${{ inputs.platform }}
