import pytest


@pytest.fixture
def connector_version(request):
    """The Snowflake Kafka Connector version under test.

    Plain fixture (no ``params=``): the default v4/v3 cross-product is supplied
    by the ``pytest_generate_tests`` hook in conftest.py. Keeping the params out
    of the fixture lets individual tests pin a subset via
    ``@pytest.mark.parametrize("connector_version", [...], indirect=True)``
    without tripping pytest>=8's "duplicate parametrization" error (a
    fixture-level ``params=`` combined with a test-level indirect override).
    """
    return request.param


@pytest.fixture
def name_salt(session_name_salt, connector_version, request):  # noqa: F811
    """Diversify names between test runs and connector versions.

    When a test has additional parametrize dimensions beyond connector_version
    (e.g. sanitize_autogenerated_table_names), all variants for the same
    connector version would otherwise share an identical name_salt and thus
    create the same Kafka topics and Snowflake tables.  Kafka topic deletion is
    asynchronous, so the second variant may observe stale data from the first.

    To prevent this, embed a short discriminator derived from the extra
    parametrize values into the salt so every variant gets a unique namespace.
    """
    base = f"{session_name_salt}_V3" if connector_version == "v3" else session_name_salt

    callspec = getattr(request.node, "callspec", None)
    if callspec is not None:
        extra_params = {
            k: v for k, v in callspec.params.items() if k != "connector_version"
        }
        if extra_params:
            # Build a short suffix from the first character of each extra param
            # value's string representation to keep names within reasonable length.
            discriminator = "_".join(str(v)[:1].upper() for v in extra_params.values())
            base = f"{base}_{discriminator}"

    return base
