import pytest


@pytest.fixture(params=["v4", "v3"])
def connector_version(request):
    """The Snowflake Kafka Connector version under test.

    Every test that (transitively) depends on this fixture is automatically run twice:
    once for v4 and once for v3.
    """
    return request.param


@pytest.fixture
def name_salt(session_name_salt, connector_version, request):  # noqa: F811
    """Diversify names between test runs and connector versions.

    When a test has additional parametrize dimensions beyond connector_version
    (e.g. sanitize_autogenerated_table_names), all variants for the same
    connector version would otherwise share an identical name_salt and thus
    create the same Kafka topics and Snowflake tables.  Kafka topic deletion is
    asynchronous, so the second variant may observe stale data from the first.

    To prevent this, embed a short discriminator derived from the extra
    parametrize values into the salt so every variant gets a unique namespace.
    """
    base = f"{session_name_salt}_V3" if connector_version == "v3" else session_name_salt

    callspec = getattr(request.node, "callspec", None)
    if callspec is not None:
        extra_params = {
            k: v for k, v in callspec.params.items() if k != "connector_version"
        }
        if extra_params:
            # Build a short suffix from the first character of each extra param
            # value's string representation to keep names within reasonable length.
            discriminator = "_".join(str(v)[:1].upper() for v in extra_params.values())
            base = f"{base}_{discriminator}"

    return base
