name: Run E2E Tests
description: Run Docker-based end-to-end tests for the Snowflake Kafka Connector

inputs:
  platform:
    description: "Target platform: 'apache' or 'confluent'"
    required: true
  platform-version:
    description: "Platform version (e.g. '2.8.2', '7.8.2')"
    required: true
  snowflake-cloud:
    description: "Snowflake cloud provider: 'AWS', 'GCP', or 'AZURE'"
    required: true
  java-version:
    description: "Java version for Apache Kafka (e.g. '11', '17'). Ignored for Confluent."
    required: false
    default: '11'
  pressure:
    description: "Run pressure/stress tests instead of regular tests"
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Run end-to-end tests
      shell: bash
      working-directory: test/docker
      env:
        SNOWFLAKE_CREDENTIAL_FILE: "${{ github.workspace }}/profile.json"
        PLATFORM: ${{ inputs.platform }}
        PLATFORM_VERSION: ${{ inputs['platform-version'] }}
        SNOWFLAKE_CLOUD: ${{ inputs['snowflake-cloud'] }}
        JAVA_VERSION: ${{ inputs['java-version'] }}
        LOGS_DIR: "${{ github.workspace }}/test-logs"
      run: |
        ./run_tests.sh \
          --platform="$PLATFORM" \
          --version="$PLATFORM_VERSION" \
          --cloud="$SNOWFLAKE_CLOUD" \
          --java-version="$JAVA_VERSION" \
          --logs-dir="$LOGS_DIR" \
          ${{ inputs.pressure == 'true' && '--pressure' || '' }}

    - name: Upload service logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ inputs.platform }}-${{ inputs['platform-version'] }}-${{ inputs['snowflake-cloud'] }}
        path: ${{ github.workspace }}/test-logs/
        retention-days: 14
        if-no-files-found: ignore
