"""E2E test: KC task should recover after channel invalidation, not die.

Reproduces the bug where AppendRowWithRetryAndFallbackPolicy successfully
recovers a channel after InvalidChannelError but re-throws the exception,
causing the KC framework to kill the task as "unrecoverable".
"""

import logging

import pytest

from lib.config_migration import V4_CONFIG_TEMPLATE
from lib.utils import RecordProducer
from tests.test_channel_invalidation import (
    _assert_task_running,
    _wait_for_stall,
    invalidate_channel,
)

logger = logging.getLogger(__name__)

RECORD_BATCH = 100
CONNECTOR_CONFIG = {
    **V4_CONFIG_TEMPLATE,
    "topics": "SNOWFLAKE_TEST_TOPIC",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "errors.tolerance": "none",
    "errors.log.enable": "true",
    "snowflake.validation": "client_side",
    "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true",
    "snowflake.compatibility.enable.column.identifier.normalization": "true",
}


@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
def test_channel_invalidation_recovery(
    driver,
    credentials,
    name_salt,
    create_connector,
    wait_for_rows,
):
    """Channel invalidation should not kill the KC task.

    Steps:
    1. Start connector, produce records, verify ingestion works.
    2. Invalidate channel via SYSTEM$STREAMING_CHANNEL_INVALIDATE.
    3. Send records (buffered by SDK), wait for ingestion to stall — proves
       the SDK flush failed.
    4. Drip-feed new records — appendRow throws SFException synchronously,
       triggering the Failsafe fallback → reopenChannel.
    5. Assert: task is RUNNING, new rows arrive in Snowflake.

    Without the fix (PR #1401), step 4 re-throws after recovery and kills the task.
    """
    topic = f"test_channel_invalidation_recovery{name_salt}"
    table_name = topic.upper()
    driver.createTopics(topic, partitionNum=1, replicationNum=1)

    connector = create_connector(v4_config=CONNECTOR_CONFIG)
    driver.wait_for_connector_running(connector.name)

    # -- Phase 1: Baseline ingestion --
    producer = RecordProducer(driver, topic)
    producer.send(RECORD_BATCH)
    wait_for_rows(table_name, RECORD_BATCH, connector_name=connector.name)
    rows_before = int(driver.select_number_of_records(table_name))
    logger.info(f"Phase 1: {rows_before} rows ingested")

    # -- Phase 2: Invalidate the channel --
    invalidate_channel(driver, credentials, table_name, topic, partition=0)

    # -- Phase 3: Trigger flush failure and verify stall --
    producer.send(RECORD_BATCH)
    stalled_rows = _wait_for_stall(driver, table_name, rows_before)
    assert stalled_rows == rows_before, (
        f"Expected ingestion to stall at {rows_before} rows after invalidation, "
        f"but rows advanced to {stalled_rows}. "
        f"SYSTEM$STREAMING_CHANNEL_INVALIDATE may not have taken effect."
    )

    # -- Phase 4: Trigger synchronous recovery via drip-feed --
    producer.start_continuous(batch_size=10, interval=1.0)
    wait_for_rows(table_name, rows_before + RECORD_BATCH, at_least=True, timeout=120)
    producer.stop_continuous()
    rows_after = int(driver.select_number_of_records(table_name))

    _assert_task_running(driver, connector.name)
    assert rows_after > rows_before, (
        f"No new rows after recovery (before={rows_before}, after={rows_after})"
    )
    logger.info(
        f"Recovery verified: {rows_before} → {stalled_rows} (stalled) → "
        f"{rows_after} (recovered), task RUNNING"
    )
