"""
E2E tests for first-create getClient when GET /v2/streaming/hostname
returns a body-less HTTP 404 (T1 Envoy NR).

SDK 1.8.0 does not retry get_subdomain_name 404s. KC Failsafe on
StreamingClientPools.getClient / getClientAsync retries body-less 404s
for CLIENT_CREATE_MAX_DURATION (2 minutes).

This is not a recreate test. No 410. No recreateClient.

Requires: --with-mitmproxy flag when running run_tests.sh.
"""

import logging
import os
import time
from time import sleep

import pytest

from lib.config_migration import V4_CONFIG_TEMPLATE
from lib.utils import RecordProducer

logger = logging.getLogger(__name__)

# Matches StreamingClientPools.CLIENT_CREATE_MAX_DURATION = Duration.ofMinutes(2).
CREATE_BUDGET_S = 120
FAULT_WINDOW_S = 60
FAIL_DEADLINE_S = CREATE_BUDGET_S + 60
RECORD_BATCH = 300

CONNECTOR_CONFIG = {
    **V4_CONFIG_TEMPLATE,
    "topics": "SNOWFLAKE_TEST_TOPIC",
    "tasks.max": "1",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "errors.tolerance": "none",
    "errors.log.enable": "true",
    "snowflake.validation": "client_side",
    "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true",
    "snowflake.compatibility.enable.column.identifier.normalization": "true",
    "snowflake.streaming.client.provider.override.map": "scheme:https,host:mitmproxy,port:8080",
}


@pytest.mark.fault_injection
@pytest.mark.skipif(
    not os.environ.get("MITMPROXY_CONTROL_URL"),
    reason="requires --with-mitmproxy (MITMPROXY_CONTROL_URL not set)",
)
@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
def test_getclient_retries_bodyless_hostname_404_then_recovers(
    driver,
    name_salt,
    create_connector,
    wait_for_rows,
    mitmproxy,
):
    """Hostname 404 for 60s (inside the 2 min create budget) then heal.

    start() is blocked in getClientAsync.join() while the 404 is on.
    Do not wait_for_connector_running during the fault window: Connect may
    already report RUNNING before start() returns.
    """
    if mitmproxy is None:
        pytest.skip("mitmproxy control API not reachable")

    topic = f"test_getclient_retries_bodyless_hostname_404_then_recovers{name_salt}"
    table_name = topic.upper()
    driver.createTopics(topic, partitionNum=1, replicationNum=1)

    mitmproxy.reset_counters()
    mitmproxy.enable_404_hostname()
    try:
        connector = create_connector(v4_config=CONNECTOR_CONFIG)
        sleep(FAULT_WINDOW_S)
        mitmproxy.disable_404_hostname()

        injected = mitmproxy.get_404_hostname_injected_count()
        assert injected > 0, (
            f"No hostname 404s were injected — Failsafe never looped. "
            f"count={injected} status={mitmproxy.get_status()}"
        )

        driver.wait_for_connector_running(connector.name, timeout=90)
        producer = RecordProducer(driver, topic)
        producer.send(RECORD_BATCH)
        wait_for_rows(table_name, RECORD_BATCH, connector_name=connector.name)

        status = driver.get_connector_status(connector.name)
        assert status["connector"]["state"] == "RUNNING", (
            f"Connector not RUNNING after recovery: {status}"
        )
        failed_tasks = driver.get_failed_tasks(connector.name)
        assert len(failed_tasks) == 0, f"Tasks failed after recovery: {failed_tasks}"
    finally:
        mitmproxy.disable_404_hostname()


@pytest.mark.fault_injection
@pytest.mark.skipif(
    not os.environ.get("MITMPROXY_CONTROL_URL"),
    reason="requires --with-mitmproxy (MITMPROXY_CONTROL_URL not set)",
)
@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
def test_getclient_fails_after_create_budget_when_hostname_404_persists(
    driver,
    name_salt,
    create_connector,
    mitmproxy,
):
    """Leave hostname 404 on. Task must still be retrying at 60s and FAILED by 180s."""
    if mitmproxy is None:
        pytest.skip("mitmproxy control API not reachable")

    topic = f"test_getclient_fails_after_create_budget_when_hostname_404_persists{name_salt}"
    driver.createTopics(topic, partitionNum=1, replicationNum=1)

    mitmproxy.reset_counters()
    mitmproxy.enable_404_hostname()
    try:
        connector = create_connector(v4_config=CONNECTOR_CONFIG)
        started = time.monotonic()

        sleep(FAULT_WINDOW_S)
        assert driver.get_failed_tasks(connector.name) == [], (
            f"Task FAILED inside the create budget "
            f"({FAULT_WINDOW_S}s < {CREATE_BUDGET_S}s): "
            f"{driver.get_failed_tasks(connector.name)}"
        )

        failed_tasks = []
        while time.monotonic() - started < FAIL_DEADLINE_S:
            failed_tasks = driver.get_failed_tasks(connector.name)
            if failed_tasks:
                break
            sleep(3)

        assert failed_tasks, (
            f"Expected a FAILED task within {FAIL_DEADLINE_S}s "
            f"(create budget {CREATE_BUDGET_S}s + slack). "
            f"status={driver.get_connector_status(connector.name)}"
        )

        injected = mitmproxy.get_404_hostname_injected_count()
        assert injected > 0, (
            f"Task FAILED but no hostname 404s were injected. "
            f"count={injected} status={mitmproxy.get_status()}"
        )
    finally:
        mitmproxy.disable_404_hostname()
