"""E2E tests: KC task should recover after channel invalidation via both paths.

Two recovery paths exist:
1. Async: processChannelStatus sees ERR_CHANNEL_MUST_BE_REOPENED → reopenChannel
2. Sync: SDK marks channel invalid locally after flush failure → appendRow throws
   SFException → Failsafe fallback → reopenChannel
"""

import logging
import time

import pytest

from lib.utils import RecordProducer

logger = logging.getLogger(__name__)

RECORD_BATCH = 100
CONNECTOR_CONFIG = {
    "connector.class": "com.snowflake.kafka.connector.SnowflakeStreamingSinkConnector",
    "topics": "SNOWFLAKE_TEST_TOPIC",
    "tasks.max": "1",
    "snowflake.url.name": "SNOWFLAKE_HOST",
    "snowflake.user.name": "SNOWFLAKE_USER",
    "snowflake.private.key": "SNOWFLAKE_PRIVATE_KEY",
    "snowflake.database.name": "SNOWFLAKE_DATABASE",
    "snowflake.schema.name": "SNOWFLAKE_SCHEMA",
    "snowflake.role.name": "SNOWFLAKE_ROLE",
    "key.converter": "org.apache.kafka.connect.storage.StringConverter",
    "value.converter": "org.apache.kafka.connect.json.JsonConverter",
    "value.converter.schemas.enable": "false",
    "errors.tolerance": "none",
    "errors.log.enable": "true",
    "snowflake.validation": "client_side",
    "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true",
    "snowflake.compatibility.enable.column.identifier.normalization": "true",
}


def _invalidate_channel(driver, credentials, table_name, topic):
    """Invalidate the streaming channel via SYSTEM$STREAMING_CHANNEL_INVALIDATE."""
    pipe_fqn = f"{credentials.database}.{credentials.schema}.{table_name}-STREAMING"
    channel_name = f"{table_name}_{topic}_0"
    logger.info(f"Invalidating channel={channel_name}, pipe={pipe_fqn}")

    cur = driver.snowflake_conn.cursor()
    cur.execute("USE ROLE ACCOUNTADMIN")
    result = cur.execute(
        f"SELECT SYSTEM$STREAMING_CHANNEL_INVALIDATE('{pipe_fqn}', '{channel_name}')"
    ).fetchone()[0]
    logger.info(f"Channel invalidation result: {result}")
    assert "ERR_CHANNEL_MUST_BE_REOPENED" in result, (
        f"Expected ERR_CHANNEL_MUST_BE_REOPENED but got: {result}"
    )
    cur.execute(f"USE ROLE {credentials.role}")


@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
def test_channel_invalidation_recovery_async(
    driver, credentials, name_salt, create_connector, wait_for_rows,
):
    """Async path: processChannelStatus detects ERR_CHANNEL_MUST_BE_REOPENED.

    After invalidation, appendRow buffers locally (SDK doesn't know yet).
    processChannelStatus sees non-SUCCESS status and triggers reopenChannel.
    """
    topic = f"test_channel_invalidation_recovery_async{name_salt}"
    table_name = topic.upper()
    driver.createTopics(topic, partitionNum=1, replicationNum=1)

    connector = create_connector(v4_config=CONNECTOR_CONFIG)
    driver.wait_for_connector_running(connector.name)

    producer = RecordProducer(driver, topic)
    producer.send(RECORD_BATCH)
    wait_for_rows(table_name, RECORD_BATCH, connector_name=connector.name)
    logger.info(f"Phase 1 complete: {RECORD_BATCH} rows ingested")

    _invalidate_channel(driver, credentials, table_name, topic)

    producer.send(RECORD_BATCH)
    wait_for_rows(table_name, RECORD_BATCH * 2, at_least=True, timeout=120)
    logger.info("Async recovery: task recovered via processChannelStatus")


@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
def test_channel_invalidation_recovery_sync(
    driver, credentials, name_salt, create_connector, wait_for_rows,
):
    """Sync path: appendRow throws SFException after SDK detects flush failure.

    After invalidation, we send records (buffered) then wait 40s for the SDK
    background flush to fail with STALE_CONTINUATION_TOKEN_SEQUENCER. This marks
    the channel as locally invalid. The next appendRow throws SFException
    synchronously, triggering the Failsafe fallback → reopenChannel.
    """
    topic = f"test_channel_invalidation_recovery_sync{name_salt}"
    table_name = topic.upper()
    driver.createTopics(topic, partitionNum=1, replicationNum=1)

    connector = create_connector(v4_config=CONNECTOR_CONFIG)
    driver.wait_for_connector_running(connector.name)

    producer = RecordProducer(driver, topic)
    producer.send(RECORD_BATCH)
    wait_for_rows(table_name, RECORD_BATCH, connector_name=connector.name)
    logger.info(f"Phase 1 complete: {RECORD_BATCH} rows ingested")

    _invalidate_channel(driver, credentials, table_name, topic)

    # Send records to trigger async flush failure, then wait for SDK to detect.
    producer.send(RECORD_BATCH)
    logger.info("Waiting 40s for SDK background flush to fail...")
    time.sleep(40)

    # Now appendRow will throw SFException synchronously.
    producer.send(RECORD_BATCH)
    wait_for_rows(table_name, RECORD_BATCH * 2, at_least=True, timeout=120)
    logger.info("Sync recovery: task recovered via Failsafe fallback")
