import json
import logging
from concurrent.futures import ThreadPoolExecutor, as_completed
import pytest

from lib.config_migration import V4_CONFIG_TEMPLATE

logger = logging.getLogger(__name__)

TOPIC_COUNT = 200
PARTITION_COUNT = 12
RECORD_COUNT = 10_000
THREAD_COUNT = 10


def _send_partition(driver, topic, partition, record_count):
    values = [
        json.dumps(
            {
                "numbernumbernumbernumbernumbernumbernumbernumbernumbernumbernumbernumber": str(
                    e
                )
            }
        ).encode("utf-8")
        for e in range(record_count)
    ]
    driver.sendBytesData(topic, values, [], partition)


@pytest.mark.pressure
@pytest.mark.parametrize("connector_version", ["v4"], indirect=True)
def test_pressure_init(driver, create_topics, create_custom_connector, wait_for_rows):
    test_name = "test_pressure_init"

    topics = create_topics(
        [f"{test_name}_{i}" for i in range(TOPIC_COUNT)],
        num_partitions=PARTITION_COUNT,
    )

    connector = create_custom_connector(
        test_name,
        {
            **V4_CONFIG_TEMPLATE,
            "tasks.max": "10",
            "topics.regex": f"{test_name}.*",
            "key.converter": "org.apache.kafka.connect.storage.StringConverter",
            "value.converter": "org.apache.kafka.connect.json.JsonConverter",
            "value.converter.schemas.enable": "false",
            "snowflake.validation": "server_side",
            "snowflake.compatibility.enable.autogenerated.table.name.sanitization": "true",
            "snowflake.compatibility.enable.column.identifier.normalization": "false",
            # Increase max poll interval from 5 to 10 minutes to avoid constant rebalancing.
            # This is required when we have a large number of topics across tasks.
            # We might be able to remove this once we parallelize table and pipe metadata lookups.
            "consumer.override.max.poll.interval.ms": "600000",
        },
    )

    driver.startConnectorWaitTime()

    total = TOPIC_COUNT * PARTITION_COUNT
    with ThreadPoolExecutor(max_workers=THREAD_COUNT) as executor:
        futures = [
            executor.submit(_send_partition, driver, topics[t], p, RECORD_COUNT)
            for t in range(TOPIC_COUNT)
            for p in range(PARTITION_COUNT)
        ]
        for i, future in enumerate(as_completed(futures), 1):
            future.result()
            if i % 100 == 0 or i == total:
                logger.info(f"Sent {i}/{total} partitions")

    for i, topic in enumerate(topics):
        table_name = topic.upper()
        logger.info("Verifying topic %d/%d: %s", i + 1, TOPIC_COUNT, table_name)
        wait_for_rows(
            table_name,
            PARTITION_COUNT * RECORD_COUNT,
            interval=10,
            timeout=1800,
            connector_name=connector.name,
        )
