package com.snowflake.kafka.connector.internal;

import java.util.HashMap;
import java.util.Map;

public class SchematizationTestUtils {

  public static final Map<String, String> SF_JSON_SCHEMA_FOR_TABLE_CREATION;

  static {
    SF_JSON_SCHEMA_FOR_TABLE_CREATION = new HashMap<>();
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("ID_INT8", "NUMBER");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("ID_INT8_OPTIONAL", "VARCHAR");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("ID_INT16", "NUMBER");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("\"id_int32_double_quotes\"", "NUMBER");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("ID_INT64", "NUMBER");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("FIRST_NAME", "VARCHAR");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("RATING_FLOAT32", "FLOAT");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("RATING_FLOAT64", "FLOAT");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("APPROVAL", "BOOLEAN");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("INFO_ARRAY", "ARRAY");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("INFO_MAP", "VARIANT");
    SF_JSON_SCHEMA_FOR_TABLE_CREATION.put("RECORD_METADATA", "VARIANT");
  }

  public static final Map<String, Object> CONTENT_FOR_JSON_TABLE_CREATION;

  static {
    CONTENT_FOR_JSON_TABLE_CREATION = new HashMap<>();
    CONTENT_FOR_JSON_TABLE_CREATION.put("ID_INT8", 0L);
    CONTENT_FOR_JSON_TABLE_CREATION.put("ID_INT8_OPTIONAL", null);
    CONTENT_FOR_JSON_TABLE_CREATION.put("ID_INT16", 42L);
    CONTENT_FOR_JSON_TABLE_CREATION.put("id_int32_double_quotes", 42L);
    CONTENT_FOR_JSON_TABLE_CREATION.put("ID_INT64", 42L);
    CONTENT_FOR_JSON_TABLE_CREATION.put("FIRST_NAME", "zekai");
    CONTENT_FOR_JSON_TABLE_CREATION.put("RATING_FLOAT32", 0.99);
    CONTENT_FOR_JSON_TABLE_CREATION.put("RATING_FLOAT64", 0.99);
    CONTENT_FOR_JSON_TABLE_CREATION.put("APPROVAL", true);
    CONTENT_FOR_JSON_TABLE_CREATION.put("INFO_ARRAY", "[\"a\",\"b\"]");
    CONTENT_FOR_JSON_TABLE_CREATION.put("INFO_MAP", "{\"field\":3}");
    CONTENT_FOR_JSON_TABLE_CREATION.put("RECORD_METADATA", "RECORD_METADATA_PLACE_HOLDER");
  }
}
