name: Build Apache Kafka Docker images

on:
  push:
    branches: [ master, ppopov_snow/split-e2e-test-suite ]
    paths:
      - 'test/docker/Dockerfile.apache-kafka'
      - 'test/apache_properties/**'
      - 'test/connect-log4j.properties'
      - '.github/workflows/build-apache-kafka-images.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - kafka_version: '2.8.2'
            scala_version: '2.12'
            java_version: '11'
          - kafka_version: '3.9.2'
            scala_version: '2.12'
            java_version: '17'
          - kafka_version: '4.1.1'
            scala_version: '2.13'
            java_version: '17'
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push apache-kafka:${{ matrix.kafka_version }}-java${{ matrix.java_version }}
        uses: docker/build-push-action@v6
        with:
          context: test
          file: test/docker/Dockerfile.apache-kafka
          build-args: |
            KAFKA_VERSION=${{ matrix.kafka_version }}
            SCALA_VERSION=${{ matrix.scala_version }}
            JAVA_VERSION=${{ matrix.java_version }}
          push: true
          tags: ghcr.io/snowflakedb/snowflake-kafka-connector/apache-kafka:${{ matrix.kafka_version }}-java${{ matrix.java_version }}
          cache-from: type=gha,scope=apache-kafka-${{ matrix.kafka_version }}-java${{ matrix.java_version }}
          cache-to: type=gha,mode=max,scope=apache-kafka-${{ matrix.kafka_version }}-java${{ matrix.java_version }}
