name: formatting

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: axel-op/googlejavaformat-action@fe78db8a90171b6a836449f8d0e982d5d71e5c5a # v3.6.0
        with:
          skip-commit: true
          version: v1.24.0
          args: "-n --set-exit-if-changed"

  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: pip install ruff
      - run: ruff check test/tests test/lib test/conftest.py
      - run: ruff format --check test/tests test/lib test/conftest.py

  formatting-done:
    needs: [java, python]
    runs-on: ubuntu-latest
    steps:
      - run: echo "All formatting checks passed"
