name: Kafka Connector Integration Test GCS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: "Install Java 8"
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Decrypt profile.json
        run: ./.github/scripts/decrypt_secret.sh 'gcs'
        env:
          SNOWFLAKE_GCS_TEST_PROFILE_SECRET: ${{ secrets.SNOWFLAKE_GCS_TEST_PROFILE_SECRET }}
      - name: Install Dependency
        run: |
          pip3 install --upgrade setuptools
          pip3 install requests certifi "confluent-kafka[avro,json,protobuf]>=1.5.0"
          pip3 install avro-python3 kafka-python
          pip3 install protobuf
          pip3 install --upgrade snowflake-connector-python
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
          sudo apt-get -y install jq vim
          sudo apt-get -y install protobuf-compiler

      - name: Install Squid as Proxy Server and Apache Utils for Password Authentication
        run: |
          sudo apt-get update
          sudo apt-get -y install squid3
          sudo apt-get install apache2-utils

      - name: Change squid config and run Proxy Server
        run: |
          sudo touch /etc/squid/passwords
          sudo chmod 777 /etc/squid/passwords
          sudo htpasswd -db -c /etc/squid/passwords admin test
          sudo mv .github/scripts/squid.conf /etc/squid/squid.conf
          sudo service squid start

      - name: Build with Unit and Integration Test
        env:
          JACOCO_COVERAGE: true
          SNOWFLAKE_CREDENTIAL_FILE: "../profile.json"
          SHELL: "/bin/bash"
        run: |
          cd test
          ./build_apache.sh ../../snowflake-kafka-connector

      - name: Code Coverage
        uses: codecov/codecov-action@v1