name: Kafka Connector Performance Test

on:
  schedule:
    - cron:  '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: "Install Java 8"
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
        architecture: 'x64'
    - name: Decrypt snowflake.json
      run: ./.github/scripts/perf_test_decrypt_secret.sh
      env:
        SNOWFLAKE_TEST_PROFILE_SECRET: ${{ secrets.SNOWFLAKE_TEST_PROFILE_SECRET }}
    - name: Restore Maven Cache
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install Dependency
      run: |
        pip3 install --upgrade setuptools
        pip3 install "confluent-kafka[avro]"
        pip3 install avro-python3
        pip3 install --upgrade snowflake-connector-python
        pip3 install pycrypto

    - name: Perf Test
      env:
        SNOWFLAKE_CREDENTIAL_FILE: "../profile.json"
      run: |
        cd test/perf_test
        ./scripts/run.sh

    - name: Code Coverage
      uses: codecov/codecov-action@v1



